# Generated by Django 2.0.7 on 2018-07-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
